### ISSUE TITLE
Fix wrapping of long strings

### ISSUE THREAD

**Issue by newbold** [neatnik/terminal.land#40]

**Comment by newbold** [comment]
Fixed!

```css
p {
	word-break: break-all;
	overflow-wrap: break-word;
}
```
